name = "clasicjlit"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "clasicjlit-db"
database_id = "<placeholder>" # You need to fill this in
migrations_dir = "db/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "clasicjlit-audio"
preview_bucket_name = "clasicjlit-audio-preview"
